name: Test Pre-installed Docker

# This triggers the action every time you push code to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  run-lab-part-a:
    # "ubuntu-latest" is the GitHub-hosted runner that comes with Docker
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download your repository code onto the runner
      - name: Checkout project code
        uses: actions/checkout@v4

      # --- STEP 1: Check Docker is ready & create lab folder ---
      - name: "Step 1: Check Docker & Setup"
        run: |
          echo ""
          docker --version
          docker info --format '{{.ServerVersion}}'
          docker run --rm hello-world
          mkdir module1-lab

      # --- STEP 2: pull an image and look at its layers ---
      - name: "Step 2: Pull Nginx Image & history"
        run: |
          cd module1-lab
          echo "========Docker pull command=============="
          docker pull nginx:1.28-alpine
          echo "========Docker images nginx Command======"
          docker images nginx
          echo "========Docker image history command======="
          docker image history nginx:1.28-alpine

      # --- STEP 3: Run your first container (foreground, then detached) ---
      # Note: We skip the interactive foreground blocking step (Ctrl+C) so the pipeline doesn't hang!
      - name: "Step 3: Run your first container"
        run: |
          cd module1-lab
          echo "========Run detached nginx container======="
          docker run --rm -d --name web -p 8080:80 nginx:1.28-alpine
          docker ps --filter "name=web"
          echo "========Check container logs======="
          sleep 3 # Give nginx a moment to wakeup
          curl -s http://localhost:8080 |grep title 
          echo "========docker logs ================"
          docker logs web 

          # --- STEP 4: Walk through the container lifecycle ---
      - name: "Step 4: Pause, Unpause, Stop Lifecycle"
        run: |
          cd module1-lab
          docker inspect -f '{{.State.Status}}' web
          docker pause web
          docker inspect -f '{{.State.Status}}' web
          docker unpause web
          docker inspect -f '{{.State.Status}}' web
          docker stop web
          docker inspect -f '{{.State.Status}} (exit code {{.State.ExitCode}})' web
          docker ps -a
          docker start web